# Pipeline to build and distribute Family Dollar Mobile App
pr: none
# specific path build
trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - family-dollar-mobile-app
    exclude:
    - README.md
    - azure-pipelines.yml

# Parameters that can be changed during build trigger
parameters:
  - name: buildIOS
    displayName: 'Build iOS?'
    type: boolean
    default: true
  - name: buildAndroid
    displayName: 'Build Android?'
    type: boolean
    default: true
  - name: deployFirebase
    displayName: 'Deploy to Firebase?'
    type: boolean
    default: true
  - name: deployBrowserstack
    displayName: 'Deploy to Browserstack?'
    type: boolean
    default: true
  - name: publishArtifacts
    displayName: 'Publish build artifacts?'
    type: boolean
    default: false
  - name: releaseVersion
    displayName: 'Release Version'
    type: string
    default: '1.0'
  - name: buildNumber
    displayName: 'Build Number'
    type: string
    default: $(Build.BuildId)
  - name: environment
    displayName: 'Environment'
    type: string
    default: 'QA'
  - name: xcodePath
    displayName: 'XCode Path'
    type: string
    default: '/Applications/Xcode_14.3.1.app'
  - name: projectPath
    displayName: 'Project Path'
    type: string
    default: '$(Build.Repository.LocalPath)/family-dollar-mobile-app/packages/family_dollar_app'
  - name: project
    displayName: 'Project'
    type: string
    default: 'family_dollar_app'
  - name: scheme
    displayName: 'Scheme'
    type: string
    default: 'family_dollar_app_qa'
  - name: config
    displayName: 'Config'
    type: string
    default: 'Release'
  - name: testGroups
    displayName: 'Notify Test Groups'
    type: string
    default: 'ps_dev,fd_dev,ps_qa,fd_qa,ps_product,fd_product'

variables:
- name: branchName
  value: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
- group: FamilyDollar_Mobile_App_Build
  
jobs:
- job: 'Code_Coverage_and_Sonar_Analysis'
  timeoutInMinutes: 60
  
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    displayName: 'Checkout FD Code Repo'
    clean: true
    fetchDepth: 1

  # Disabled test and coverage as unit test execution is failing    
  # - script: |
  #     cd family-dollar-mobile-app
  #     yarn
  #     cd packages/family_dollar_app
  #     yarn jest -u --coverage --coverageReporters=cobertura
  #   displayName: 'Run Tests'
  
  # - task: PublishCodeCoverageResults@1
  #   condition: succeededOrFailed()
  #   inputs:
  #     codeCoverageTool: Cobertura
  #     summaryFileLocation: ${{parameters.projectPath}}/coverage/cobertura-coverage.xml

  # Prepare Analysis Configuration task
  - task: SonarQubePrepare@5
    condition: succeededOrFailed()
    inputs:
      SonarQube: 'FDSonarQubeServer'
      scannerMode: 'CLI'

  # Run Code Analysis task
  - task: SonarQubeAnalyze@5
    condition: succeededOrFailed()

  # Publish Quality Gate Result task
  - task: SonarQubePublish@5
    condition: succeededOrFailed()
    inputs:
      pollingTimeoutSec: '300'

- job: 'iOS_App_Package_Build_and_Deploy'
  dependsOn: 'Code_Coverage_and_Sonar_Analysis'
  condition: eq('${{parameters.buildIOS}}', true)
  timeoutInMinutes: 60
  
  pool:
    vmImage: 'macOS-13'

  steps:
  - checkout: self
    displayName: 'Checkout FD Code Repo'
    clean: true
    fetchDepth: 1
  
  - script: |
      sudo npm install -g firebase-tools
      cd family-dollar-mobile-app
      yarn
      cd packages/family_dollar_app/ios
      sed -i -e "s|'${{parameters.project}}'|'${{parameters.scheme}}'|g" ./podfile
      bundle install && RCT_NEW_ARCH_ENABLED=0 NO_FLIPPER=1 bundle exec pod install
      cd ..
      yarn bundle:ios
    displayName: 'Install Dependencies & Create RN Bundle'

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'iOS_Distribution_Certificate.p12'
      certPwd: $(cert_pwd)
      keychain: 'temp'
    displayName: 'Install Code Signing Certificate'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'Family_Dollar_QA_Adhoc_Dist.mobileprovision'
    displayName: 'Install App Provisioning Profile'
  
  - task: Bash@3
    env:
      BuildNumber: ${{parameters.buildNumber}}
      AppVersion: ${{parameters.releaseVersion}}
      XCODEPATH: ${{parameters.xcodePath}}
      DEVELOPER_DIR: ${{parameters.xcodePath}}/Contents/Developer
    inputs:
      targetType: 'inline'
      script: |
        # Setting build concurrency to 6 (2 times the number of cores on the macos agent)
        defaults write com.apple.dt.xcodebuild IDEBuildOperationMaxNumberOfConcurrentCompileTask 6
        defaults write com.apple.dt.xcodebuild PBXNumberOfParallelBuildSubtasks 6
        defaults write com.apple.dt.Xcode PBXNumberOfParallelBuildSubtasks 6
        defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks 6

        # switching xcode to the version configured above in parameters
        sudo xcode-select -s ${{parameters.xcodePath}}
        xcode-select -p

        cd ${{parameters.projectPath}}/ios

        # find and replace app and build version in the xcode project file
        sed -i -e 's|$AppVersion|'$AppVersion'|g' ./${{parameters.project}}.xcodeproj/project.pbxproj
        sed -i -e 's|$BuildNumber|'$BuildNumber'|g' ./${{parameters.project}}.xcodeproj/project.pbxproj

        # build and archive
        xcodebuild archive \
          -workspace ${{parameters.project}}.xcworkspace \
          -scheme ${{parameters.scheme}} \
          -archivePath ${{parameters.projectPath}}/ios/FamilyDollar.xcarchive \
          -destination generic/platform=iOS \
          -configuration ${{parameters.config}} \
          -derivedDataPath $(Build.Repository.LocalPath)
        
        # export the archive
        xcodebuild -exportArchive \
          -archivePath ${{parameters.projectPath}}/ios/FamilyDollar.xcarchive \
          -exportOptionsPlist ${{parameters.projectPath}}/ios/Configs/qa/ExportOptions.plist \
          -exportPath ${{parameters.projectPath}}/ios \
          -destination generic/platform=iOS
        
        # rename the IPA file to suffix version
        mv ${{parameters.projectPath}}/ios/${{parameters.scheme}}.ipa \
          ${{parameters.projectPath}}/ios/QA_FamilyDollar_v${{parameters.releaseVersion}}.${{parameters.buildNumber}}.ipa
    displayName: 'Build, Archive & Export Package'
  
  # - task: ArchiveFiles@2
  #   inputs:
  #     rootFolderOrFile: '${{parameters.projectPath}}/ios/FamilyDollar.xcarchive' 
  #     includeRootFolder: true 
  #     archiveType: 'zip' # Options: zip, 7z, tar, wim
  #     tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
  #     archiveFile: '$(Build.ArtifactStagingDirectory)/FamilyDollar.xcarchive.zip' 
  #     replaceExistingArchive: true
  #   displayName: 'Copy XCArchive to staging directory'

  - task: CopyFiles@2
    inputs:
      contents: '${{parameters.projectPath}}/ios/*.ipa'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy IPA to staging directory'

  - script: |
      curl -u $(browserstack_user) \
        -X POST https://api-cloud.browserstack.com/app-live/upload \
        -F file=@${{parameters.projectPath}}/ios/QA_FamilyDollar_v${{parameters.releaseVersion}}.${{parameters.buildNumber}}.ipa
    displayName: 'Deploy to Browserstack App-Live'
    condition: and(eq('${{parameters.deployBrowserstack}}', true), eq(variables['branchName'], 'develop'))

  - script: |
      firebase appdistribution:distribute ${{parameters.projectPath}}/ios/QA_FamilyDollar_v${{parameters.releaseVersion}}.${{parameters.buildNumber}}.ipa \
        --app 1:546665870578:ios:f1fa784f5559f3daebcc6b \
        --groups "${{parameters.testGroups}}" \
        --release-notes "Build deployed from ADO pipeline" \
        --token $(firebase_ci_token)
    displayName: 'Deploy to Firebase'
    condition: and(eq('${{parameters.deployFirebase}}', true), eq(variables['branchName'],'develop'))
    
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    condition: and(succeededOrFailed(), eq('${{parameters.publishArtifacts}}', true))

- job: 'Android_App_Package_Build_and_Deploy'
  dependsOn: 'Code_Coverage_and_Sonar_Analysis'
  condition: eq('${{parameters.buildAndroid}}', true)
  timeoutInMinutes: 60
  
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    displayName: 'Checkout FD Code Repo'
    clean: true
    fetchDepth: 1

  - script: |
      sudo npm install -g firebase-tools
      cd family-dollar-mobile-app
      yarn

      # find and replace app version code in the build.gradle file
      sed -i -e 's|versionCode versCode as Integer|versionCode ${{parameters.buildNumber}}|g' ${{parameters.projectPath}}/android/app/build.gradle
    displayName: 'Install Dependencies'

  - task: Gradle@3
    displayName: 'Build APK'
    inputs:
      gradleWrapperFile: '${{parameters.projectPath}}/android/gradlew'
      workingDirectory: '${{parameters.projectPath}}/android/'
      options: '-PversName=${{parameters.releaseVersion}} -PversCode=${{parameters.buildNumber}}'
      tasks: 'app:assembleQa${{parameters.config}} --parallel --max-workers=8'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false

  # - task: AndroidSigning@3
  #   displayName: 'Sign APK'
  #   inputs:
  #     apkFiles: '${{parameters.projectPath}}/android/app/build/outputs/apk/release/*.apk'
  #     apksignerKeystoreFile: 'mobile-prod.keystore'
  #     apksignerKeystorePassword: '$(AndroidKeyStorePassword)'
  #     apksignerKeystoreAlias: '$(AndroidKeyAlias)'
  #     apksignerKeyPassword: '$(AndroidKeyAliasPassword)'
  #     zipalign: true

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # rename the APK file to suffix version
        mv ${{parameters.projectPath}}/android/app/build/outputs/apk/qa/${{lower(parameters.config)}}/app-qa-${{lower(parameters.config)}}.apk \
          ${{parameters.projectPath}}/android/QA_FamilyDollar_v${{parameters.releaseVersion}}.${{parameters.buildNumber}}.apk
    displayName: 'Rename APK File'
  
  - task: CopyFiles@2
    inputs:
      contents: '${{parameters.projectPath}}/android/*.apk'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy APK to staging directory'

  - script: |
      curl -u $(browserstack_user) \
        -X POST https://api-cloud.browserstack.com/app-live/upload \
        -F file=@${{parameters.projectPath}}/android/QA_FamilyDollar_v${{parameters.releaseVersion}}.${{parameters.buildNumber}}.apk
    displayName: 'Deploy to Browserstack App-Live'
    condition: and(eq('${{parameters.deployBrowserstack}}', true), eq(variables['branchName'],'develop'))

  - script: |
      firebase appdistribution:distribute ${{parameters.projectPath}}/android/QA_FamilyDollar_v${{parameters.releaseVersion}}.${{parameters.buildNumber}}.apk \
        --app 1:546665870578:android:e0e819b902711ffbebcc6b \
        --groups "${{parameters.testGroups}}" \
        --release-notes "Build deployed from ADO pipeline" \
        --token $(firebase_ci_token)
    displayName: 'Deploy to Firebase'
    condition: and(eq('${{parameters.deployFirebase}}', true), eq(variables['branchName'],'develop'))
    
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    condition: and(succeededOrFailed(), eq('${{parameters.publishArtifacts}}', true))
