library identifier: 'dollar-tree-pipeline-library@infra', changelog: false, retriever: modernSCM(
        [$class       : 'GitSCMSource',
         remote       : 'https://github.com/Family-Dollar/FD-platform-build.git',
         credentialsId: 'github_pat']) _

properties([
  parameters([
    string(defaultValue: 'dollar-tree-i', description: 'Namespace to deploy redis-sentinel eg: dollar-tree-i', name: 'NAMESPACE', trim: true),
    string(defaultValue: '17.11.5', description: 'Chart version to use', name: 'CHART_VERSION', trim: true)
    ])
])

node {
    scmCheckout()
    deployRedis namespace: params.NAMESPACE, chartVersion: params.CHART_VERSION
}