library identifier: 'dollar-tree-pipeline-library@infra', changelog: false, retriever: modernSCM(
        [$class       : 'GitSCMSource',
         remote       : 'https://github.com/Family-Dollar/FD-platform-build.git',
         credentialsId: 'github_pat']) _

properties([
  parameters([
    string(defaultValue: '1.18.0', description: 'Chart version to use', name: 'CHART_VERSION', trim: true)
    ])
])
node {
    scmCheckout()
    deployIstioIngress chartVersion: params.CHART_VERSION
}