{{- if .Values.mtls.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "app.fullname" . }}
spec:
  host: {{ include "app.fullname" . }}.{{.Release.Namespace}}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}